#!/usr/bin/env ruby

git_bundles = [ 
  'git://github.com/tpope/vim-sensible.git',
  'http://github.com/mattn/emmet-vim.git',
  'https://github.com/derekwyatt/vim-scala.git',
  'https://github.com/jelera/vim-javascript-syntax.git',
  'https://github.com/kchmck/vim-coffee-script.git',
  'https://github.com/mtscout6/vim-cjsx.git',
  'https://github.com/scrooloose/syntastic.git',
  'https://github.com/wlangstroth/vim-racket.git',
]

vim_org_scripts = [
  [],
  [],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
